import 'package:get/get.dart';

class LocalString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en':{
      'welcome':'Welcome back',                   // english
      'sign_in':'Sign in to continue',
      'email':'Email',
      'enter_email':'Enter Email',
      'password':'Password',
      'enter_password':'Enter Password',
      'forget_password':'Forget Password',
      'sign_in_text':'Sign In',
    },
    'es':{                                        // spanish
      'welcome':'Bienvenido de nuevo',
      'sign_in':'Inicia sesión para continuar',
      'email':'Correo electrónico',
      'enter_email':'Ingrese correo electrónico',
      'password':'Contraseña',
      'enter_password':'Introducir la contraseña',
      'forget_password':'Contraseña olvidada',
      'sign_in_text':'Iniciar sesión',
    },
    'hi':{
      'welcome':'वापसी पर स्वागत है',
      'sign_in':'जारी रखने के लिए साइन इन करें',
      'email':'ईमेल',
      'enter_email':'ईमेल दर्ज करें',
      'password':'पासवर्ड',
      'enter_password':'पासवर्ड दर्ज करें',
      'forget_password':'पासवर्ड भूल गए',
      'sign_in_text':'दाखिल करना',
    },
    'ar':{
      'welcome':'مرحبًا بعودتك',
      'sign_in':'تسجيل الدخول للمتابعة',
      'email':'بريد إلكتروني',
      'enter_email':'أدخل البريد الإلكتروني',
      'password':'كلمة المرور',
      'enter_password':'أدخل كلمة المرور',
      'forget_password':'نسيت كلمة المرور',
      'sign_in_text':'تسجيل الدخول',
    },
    'zh':{
      'welcome':'欢迎回来',
      'sign_in':'登录以继续',
      'email':'电子邮件',
      'enter_email':'输入电子邮件',
      'password':'密码',
      'enter_password':'输入密码',
      'forget_password':'忘记密码',
      'sign_in_text':'登入',
    },
    'de':{
      'welcome':'Willkommen zurück',
      'sign_in':'Melden Sie sich an, um fortzufahren',
      'email':'Email',
      'enter_email':'Email eingeben',
      'password':'Passwort',
      'enter_password':'Passwort eingeben',
      'forget_password':'Passwort vergessen',
      'sign_in_text':'Anmelden',
    },
    'fr':{
      'welcome':'Content de te revoir',
      'sign_in':'Connectez-vous pour continuer',
      'email':'E-mail',
      'enter_email':'Entrez votre e-mail',
      'password':'Mot de passe',
      'enter_password':'Entrer le mot de passe',
      'forget_password':'Mot de passe oublié',
      'sign_in_text':'Se connecter',
    },
    'it':{
      'welcome':'Bentornato',
      'sign_in':'Accedi per continuare',
      'email':'E-mail',
      'enter_email':"Inserisci l'email",
      'password':"Parola d'ordine",
      'enter_password':'Inserire la password',
      'forget_password':'Dimenticare la password',
      'sign_in_text':'Registrazione',
    },
    'ur':{
      'welcome':'خوش آمدید',
      'sign_in':'جاری رکھنے کے لیے سائن ان کریں۔',
      'email':'ای میل',
      'enter_email':'ای میل درج کریں۔',
      'password':'پاس ورڈ',
      'enter_password':'پاس ورڈ درج کریں',
      'forget_password':'پاس ورڈ بھول جانا',
      'sign_in_text':'سائن ان',
    },
    'bn':{
      'welcome':'ফিরে আসার জন্য স্বাগতম',
      'sign_in':'চালিয়ে যেতে সাইন ইন করুন',
      'email':'ইমেইল',
      'enter_email':'ইমেইল প্রদান করুন',
      'password':'পাসওয়ার্ড',
      'enter_password':'পাসওয়ার্ড লিখুন',
      'forget_password':'পাসওয়ার্ড ভুলে গেছেন',
      'sign_in_text':'সাইন ইন করুন',
    }
  };
}