import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en': {
          'welcome': 'Welcome back',
          'sign_in': 'Sign in to continue',
          'email': 'Email',
          'enter_email': 'Enter Email',
          'password': 'Password',
          'enter_password': 'Enter Password',
          'forget_password': 'Forget Password',
          'change_password': 'Change Password',
          'continue': 'Continue',
          'sign_in_text': 'Sign In',
          'email_validation': 'Email ID is Incorrect',
          'password_validation': 'Wrong password',
          'forgot_password_details':
              'Enter your registered email and will send you instructions on how to reset it',
          'forgot_password_email_validation':
              'We have not found any account associated with this email address',
          'password_not_matched': 'Passwords not matched!',
          'password_short_password': 'Passwords is too short!',
          'password_matched': 'Passwords matched!',
          'password_successfully_changed': 'Password Changed Successfully!',
          'account_accessible': 'You can now log-in to your SGT account',
          'Home': 'Home',
          'connect': 'Connect',
          'notification': 'Notifications',
          'account': 'Account',
          'back_to_login': 'Back To Log In',
          'no_internet': 'No Internet Connection.',
          'team': 'Team',
          'see_all': 'See all',
          'my_teams': "My Team's",
          'active_property': 'Active Property',
          'inactive_property': 'Inactive Property',
          'active': 'Active',
          'Inactive': 'Inactive',
          'timesheet': 'Timesheet',
          'upcoming': 'Upcoming',
          'completed': 'Completed',
          'location': 'Location',
          'leave_status': 'Leave Status',
          'active_tours': 'Active Tours',
          'upcoming_tours': 'Upcoming Tours',
          'active_property_map_view': 'Active Property Map View',
          'general_report': 'General Report',
          'maintanance_report': 'Maintenance Report',
          'parking_report': 'Parking Report',
          'emergency_report': 'Emergency Report',
          'upcoming_shift': 'Upcoming Shifts',
          'missed_shifts': 'Missed Shifts',
          'last_shift': 'Last Shift',
          'approved_by': 'Approved by',
          'approved_on': 'Approved on',
          'approved_at': 'Approved at',
          'go_back': 'Go Back',
          'leave_subject': 'Leave Subject',
          'rejected_by': 'Rejected by',
          'rejected_on': 'Rejected on',
          'rejected_at': 'Rejected at',
          'rejection_reason': 'Reason Of Rejection',
          'pending': 'Pending',
          'cancel': 'Cancel',
          'leave_request_cancelation':
              'Are you sure you want to cancel leave request?',
          'yes': 'Yes',
          'no': 'No',
          'active_properties': 'Active Properties',
          'missed': 'Missed',
          'missed_shift': 'Missed Shift',
          'job_details': 'Job Details',
          'guard_name': 'Guard Name',
          'position': 'Position',
          'shift_time': 'Shift time',
          'description': 'Description',
          'shift_time_text': 'Your Shift Time',
          'completed_checkpoints': 'Completed Checkpoints',
          'missed_checkpoints': 'Missed Checkpoint',
          'clock_in_time': 'Clock In Time',
          'clock_out_time': 'Clock out Time',
          'view_report': 'View Reports',
          'all_reports': 'All Reports',
          'report_type': 'Report Type',
          'select_report_type_text': 'Select report type below',
          'guard': 'Guards',
          'checkpoint': 'Checkpoints',
          'sqft': 'Sqft',
          'scan_qr': 'Scan QR',
          'report': 'Report',
          'emergency_contact': 'Emergency Contact',
          'show_less': 'Show less',
          'show_more': 'Show more',
          'contact': 'Contact',
          'shift_details': 'Shift Details',
          'shift_timing': 'Shift Timing',
          'property': 'Property',
          'shift_description': 'Shift Description',
          'checkpoint_shift_validation':
              'To view checkpoint details you have to start the shift!',
          'job_guideline': "Job Guideline's",
          'start_shift': 'Start Shift',
          'report_type_text': 'Select report type below',
          'shift_report': 'Shift Report',
          'next': 'Next',
          'property_name': 'Property Name',
          'subject': 'Subject',
          'notes': 'Notes',
          'sample_upload_image_text': 'Upload Record Sample*',
          'choose_file_text': 'Choose a File',
          'send': 'Send',
          'manufacturer': 'Manufacturer',
          'manufacturer_hint': 'Type here manufacturer',
          'model': 'Model',
          'color': 'Color',
          'license_number': 'License Number',
          'state': 'State',
          'towed': 'Towed',
          'emergency_date_time': 'Emergency Date & Time',
          'date': 'Date',
          'time': 'Time',
          'edit_location': 'Edit Location',
          'emergency_details': 'Emergency Details',
          'people_involved': 'People Involved',
          'name': 'Name',
          'phone_number': 'Phone Number',
          'add_people': 'Add People',
          'witnesses': 'Witnesses',
          'add_witness': 'Add Witness',
          'action_taken': 'Action Taken',
          'police_report': 'Police Report',
          'officer_name': 'Officer Name',
          'officer': 'Officer',
          'select_time': 'Select Time',
          'ok': 'OK',
          'use_pinned_location': 'Use pinned location',
          'done': 'Done',
          'report_submit_successful_text': 'Report has been sent successfully!',
          'qr_scan': 'QR Scan',
          'clock_in': 'Clock in',
          'clock_in_description': 'Scan QR code to clock in!',
          'clock_in_qr_validation': 'Something went wrong. Please try again',
          're_scan': 'Re-Scan',
          'check_in_error': 'ERROR',
          'check_in_error_description':
              'You are not in your designated location to begin your shift',
          'day': 'Day',
          'shift_location_text': 'Check your shift location',
          'back': 'Back',
          'clocked_in': 'Clocked In',
          'check_in_success_description':
              'You are currently clocked in and ready to go!',
          'guard_post_duties': 'Guard Post Duties',
          'hours': 'Hours',
          'minutes': 'Minutes',
          'seconds': 'Seconds',
          'clock_out_button': 'Clock Out',
          'remaining_shift_time': 'Remaining Shift Time',
          'start': 'Start',
          'check_in': 'Check in',
          'checkpoint_qr_scan_text': 'Scan QR code to view checkpoint details',
          'tasks': 'Tasks',
          'add_report': 'Add a report',
          'upload_image': 'Upload Image',
          'select_media': 'Select Media From?',
          'select_media_description':
              'Use camera or select file from device gallery',
          'camera': 'Camera',
          'gallery': 'Gallery',
          'save': 'Save',
          'confirmed': 'Confirmed',
          'checkpoint_complete_successful': 'Checkpoint Completed Successful',
          'route_no': 'Route No',
          'clock_out': 'Clock Out',
          'clocked_in_successful_text':
              'You are currently clocked in and ready to go! ',
          'clocked_out_successful_text':
              'You are currently clocked out from shift!',
          'total_time': 'Total Time',
          'all_checkpoints_not_completed_text':
              'You have not completed all checkpoints!',
          'remaining_checkpoints': 'Remaining Checkpoints',
          'without_complete_checkpoint_clockout_text':
              'You want to clock out without completing your duty?',
          'mark_all_as_read': 'Mark All As Read',
          'chats': 'Chats',
          'selected': 'Selected',
          'share_to': 'Share to',
          'delete_media_permission_message':
              'Delete media? Are you sure you want to delete this media?',
          'delete': 'Delete ',
          'write_message': 'Write a message',
          'duty': 'Duty',
          'general': 'General',
          'personal': 'Personal',
          'address': 'Address',
          'street': 'Street',
          'city': 'City',
          'zipcode': 'Zipcode',
          'guard_id_card': 'Guard ID Card',
          'weapon_permit': 'Weapon Permit',
          'guard_cards': 'Guard Cards',
          'settings': 'Settings',
          'edit_account_details': 'Edit Account Details',
          'apply_leave': 'Apply Leave',
          'reports': 'Reports',
          'terms_and_conditions': 'Terms & Conditions',
          'privacy_policy': 'Privacy Policy',
          'language': 'Language',
          'help_and_support': 'Help & Support',
          'sign_out': 'Sign Out',
          'notification_alert': 'Notification Alert ',
          'text_messages': 'Text Messages',
          'add_guard_card': 'Add Gaurd Card',
          'required_field': 'Please fill this field!',
          'required_email_text': 'Please enter valid email address!',
          'required_phone_no_text': 'Please enter valid mobile number!',
          'required_upload_guard_card': 'Please upload your card!',
          'your_reports': 'Your Reports',
          'recent_reports': 'Recents Reports',
          'filters': 'Filters',
          'title': 'Title',
          'by_property': 'By Property View',
          'date_range': 'Date Range',
          'from': 'From',
          'to': 'To',
          'old_password': 'Old Password',
          'new_password': 'New Password',
          're_enter_new_password': 'Re-enter New Password',
          'changed': 'Changed',
          'search_language': 'Search Langauge ',
          'log_out_permission_text': 'Are You Sure! You want to sign out?',
          'request_logout_task_pending_text':
              'Your shift is not completed. Tasks are pending.',
          'leave_from': 'Leave From',
          'terms_and_condition_accepting_message':
              'I accepted the terms and conditions. Do not apply leave if you do not agree to take all of the terms and conditions stated on this page.',
          'total_missing_shifts_on_leave': 'Total Missing Shifts On Leave',
          'leave_reason': 'Reason Of Leave',
          'shifts_between_dates': 'Shifts Between Dates',
          'sent_successfully': 'Sent Successfully',
          'approval_wait_text': 'Wait for approval!',
          //new Keywords 20-05
          'enter_registered_email':'Please enter registered email',
          'please_enter_password':'Please enter password',
          'location_not_available':'Location Not Available',
          'enter_valid_password':'Enter Valid password',
          
        },
        'es': {
          // spanish
          'welcome': 'Bienvenido de nuevo',
          'sign_in': 'Inicia sesión para continuar',
          'email': 'Correo electrónico',
          'enter_email': 'Ingrese correo electrónico',
          'password': 'Contraseña',
          'enter_password': 'Introducir la contraseña',
          'forget_password': 'Contraseña olvidada',
          'sign_in_text': 'Iniciar sesión',
        },
        'hi': {
          'welcome': 'वापसी का स्वागत',
          'sign_in': 'जारी रखने के लिए साइन इन करें',
          'email': 'ईमेल',
          'enter_email': 'ईमेल दर्ज करें',
          'password': 'पासवर्ड',
          'enter_password': 'पासवर्ड दर्ज करें',
          'forget_password': 'पासवर्ड भूल गए',
          'change_password': 'पासवर्ड बदलें',
          'continue': 'जारी रखें',
          'sign_in_text': 'साइन इन करें',
          'email_validation': 'ईमेल आईडी गलत है',
          'password_validation': 'गलत पासवर्ड',
          'forgot_password_details':
              'अपना पंजीकृत ईमेल दर्ज करें और हम आपको रीसेट करने के लिए निर्देश भेजेंगे',
          'forgot_password_email_validation':
              'हमें इस ईमेल पते से संबंधित कोई खाता नहीं मिला',
          'password_not_matched': 'पासवर्ड मेल नहीं खाते!',
          'password_short_password': 'पासवर्ड बहुत छोटा है!',
          'password_matched': 'पासवर्ड मिल गया!',
          'password_successfully_changed': 'पासवर्ड सफलतापूर्वक बदल दिया गया!',
          'account_accessible': 'अब आप अपने SGT खाते में लॉग-इन कर सकते हैं',
          'Home': 'होम',
          'timesheet': 'टाइमशीट',
          'connect': 'कनेक्ट',
          'notification': 'सूचनाएँ',
          'account': 'खाता',
          'back_to_login': 'लॉगिन पर वापस जाएं',
          'no_internet': 'कोई इंटरनेट कनेक्शन नहीं।',
          'team': 'टीम',
          'see_all': 'सभी देखें',
          'my_teams': "मेरी टीमों",
          'active_property': 'सक्रिय संपत्ति',
          'inactive_property': 'निष्क्रिय संपत्ति',
          'active': 'सक्रिय',
          'Inactive': 'निष्क्रिय',
          'upcoming': 'आगामी',
          'completed': 'पूरा किया',
          'location': 'स्थान',
          'leave_status': 'छुट्टी की स्थिति',
          'active_tours': 'सक्रिय यात्राएं',
          'upcoming_tours': 'आगामी यात्राएं',
          'active_property_map_view': 'सक्रिय संपत्ति का नक्शा देखें',
          'general_report': 'सामान्य रिपोर्ट',
          'maintanance_report': 'रखरखाव रिपोर्ट',
          'parking_report': 'पार्किंग रिपोर्ट',
          'emergency_report': 'आपातकालीन रिपोर्ट',
          'upcoming_shift': 'आगामी शिफ्ट',
          'missed_shifts': 'छूटी हुई शिफ्टें',
          'last_shift': 'आखिरी शिफ्ट',
          'approved_by': 'द्वारा मंजूर',
          'approved_on': 'पर मंजूर किया गया',
          'approved_at': 'मंजूर किया गया',
          'go_back': 'पिछवाड़े जाएं',
          'leave_subject': 'छुट्टी का विषय',
          'rejected_by': 'द्वारा अस्वीकृत',
          'rejected_on': 'पर अस्वीकृत',
          'rejected_at': 'पर अस्वीकृत',
          'rejection_reason': 'अस्वीकृति का कारण',
          'pending': 'विचाराधीन',
          'cancel': 'रद्द करें',
          'leave_request_cancelation':
              'क्या आप वाकई छुट्टी का अनुरोध रद्द करना चाहते हैं?',
          'yes': 'हाँ',
          'no': 'नहीं',
          'active_properties': 'सक्रिय संपत्तियाँ',
          'missed': 'छूट गया',
          'missed_shift': 'छूट गई शिफ्ट',
          'job_details': 'नौकरी का विवरण',
          'guard_name': 'गार्ड का नाम',
          'position': 'स्थिति',
          'shift_time': 'शिफ्ट का समय',
          'description': 'विवरण',
          'shift_time_text': 'आपका शिफ्ट समय',
          'completed_checkpoints': 'पूरा किए गए चेकप्वाइंट्स',
          'missed_checkpoints': 'छूटे हुए चेकप्वाइंट',
          'clock_in_time': 'क्लॉक इन समय',
          'clock_out_time': 'क्लॉक आउट समय',
          'view_report': 'रिपोर्ट देखें',
          'all_reports': 'सभी रिपोर्ट्स',
          'report_type': 'रिपोर्ट का प्रकार',
          'select_report_type_text': 'नीचे रिपोर्ट का प्रकार चुनें',
          'guard': 'गार्ड',
          'checkpoint': 'चेकप्वाइंट',
          'sqft': 'शिफ्ट',
          'scan_qr': 'क्यूआर स्कैन करें',
          'report': 'रिपोर्ट',
          'emergency_contact': 'आपातकालीन संपर्क',
          'show_less': 'कम दिखाएं',
          'show_more': 'अधिक दिखाएं',
          'contact': 'संपर्क करें',
          'shift_details': 'शिफ्ट विवरण',
          'shift_timing': 'शिफ्ट समय',
          'property': 'संपत्ति',
          'shift_description': 'शिफ्ट विवरण',
          'checkpoint_shift_validation':
              'चेकपॉइंट विवरण देखने के लिए आपको शिफ्ट शुरू करना होगा!',
          'job_guideline': "नौकरी के निर्देशों",
          'start_shift': 'शिफ्ट शुरू करें',
          'report_type_text': 'नीचे रिपोर्ट का प्रकार चुनें',
          'shift_report': 'शिफ्ट रिपोर्ट',
          'next': 'अगला',
          'property_name': 'संपत्ति का नाम',
          'subject': 'विषय',
          'notes': 'टिप्पणियाँ',
          'sample_upload_image_text': 'रेकॉर्ड सैंपल अपलोड करें*',
          'choose_file_text': 'एक फ़ाइल चुनें',
          'send': 'भेजें',
          'manufacturer': 'निर्माता',
          'manufacturer_hint': 'यहाँ निर्माता लिखें',
          'model': 'मॉडल',
          'color': 'रंग',
          'license_number': 'लाइसेंस संख्या',
          'state': 'राज्य',
          'towed': 'खींचा गया',
          'emergency_date_time': 'आपातकालीन तारीख और समय',
          'date': 'तारीख',
          'time': 'समय',
          'edit_location': 'स्थान संपादित करें',
          'emergency_details': 'आपातकालीन विवरण',
          'people_involved': 'शामिल हुए लोग',
          'name': 'नाम',
          'phone_number': 'फ़ोन नंबर',
          'add_people': 'लोग जोड़ें',
          'witnesses': 'गवाह',
          'add_witness': 'गवाह जोड़ें',
          'action_taken': 'कार्रवाई की गई',
          'police_report': 'पुलिस रिपोर्ट',
          'officer_name': 'ऑफिसर का नाम',
          'officer': 'ऑफिसर',
          'select_time': 'समय चुनें',
          'ok': 'ठीक है',
          'use_pinned_location': 'पिन किए गए स्थान का उपयोग करें',
          'done': 'संपन्न',
          'report_submit_successful_text': 'रिपोर्ट सफलतापूर्वक भेजी गई है!',
          'qr_scan': 'क्यूआर स्कैन',
          'clock_in': 'क्लॉक इन',
          'clock_in_description': 'क्लॉक इन करने के लिए क्यूआर को स्कैन करें!',
          'clock_in_qr_validation': 'कुछ गलत हो गया है। कृपया पुनः प्रयास करें',
          're_scan': 'पुनः स्कैन करें',
          'check_in_error': 'त्रुटि',
          'check_in_error_description':
              'आप अपने निर्धारित स्थान में नहीं हैं शिफ्ट शुरू करने के लिए',
          'day': 'दिन',
          'shift_location_text': 'अपने शिफ्ट स्थान को जांचें',
          'back': 'पीछे',
          'clocked_in': 'क्लॉक इन हुआ',
          'check_in_success_description':
              'आप वर्तमान में क्लॉक इन किए गए हैं और तैयार हैं!',
          'guard_post_duties': 'गार्ड पोस्ट कर्तव्य',
          'hours': 'घंटे',
          'minutes': 'मिनट',
          'seconds': 'सेकंड्स',
          'clock_out_button': 'क्लॉक आउट',
          'start': 'शुरू करें',
          'check_in': 'चेक इन',
          'checkpoint_qr_scan_text':
              'चेकपॉइंट विवरण देखने के लिए क्यूआर को स्कैन करें',
          'tasks': 'कार्य',
          'add_report': 'रिपोर्ट जोड़ें',
          'upload_image': 'छवि अपलोड करें',
          'select_media': 'सामग्री का चयन करें?',
          'select_media_description':
              'कैमरा का उपयोग करें या उपकरण गैलरी से फ़ाइल का चयन करें',
          'camera': 'कैमरा',
          'gallery': 'गैलरी',
          'save': 'सहेजें',
          'confirmend': 'पुष्टि की',
          'checkpoint_complete_successful': 'चेकपॉइंट सफलतापूर्वक पूरा हुआ',
          'route_no': 'रूट नंबर',
          'remaining_shift_time': 'बचा हुआ शिफ्ट समय',
          'clock_out': 'क्लॉक आउट',
          'clocked_in_successful_text':
              'आप वर्तमान में क्लॉक इन किए गए हैं और तैयार हैं! ',
          'clocked_out_successful_text':
              'आप वर्तमान में शिफ्ट से क्लॉक आउट हैं!',
          'total_time': 'कुल समय',
          'all_checkpoints_not_completed_text':
              'आपने सभी चेकपॉइंट्स पूरे नहीं किए हैं!',
          'remaining_checkpoints': 'बचे हुए चेकपॉइंट्स',
          'without_complete_checkpoint_clockout_text':
              'आप बिना अपना ड्यूटी पूरी किए क्लॉक आउट करना चाहते हैं?',
          'mark_all_as_read': 'सभी को पढ़ा चिह्नित करें',
          'chats': 'चैट्स',
          'selected': 'चयनित',
          'share_to': 'को साझा करें',
          'delete_media_permission_message':
              'मीडिया हटाएं? क्या आप वाकई इस मीडिया को हटाना चाहते हैं?',
          'delete': 'हटाएं ',
          'write_message': 'संदेश लिखें',
          'duty': 'ड्यूटी',
          'general': 'सामान्य',
          'personal': 'व्यक्तिगत',
          'address': 'पता',
          'street': 'सड़क',
          'city': 'शहर',
          'zipcode': 'पिन कोड',
          'guard_id_card': 'गार्ड आईडी कार्ड',
          'weapon_permit': 'हथियार परमिट',
          'guard_cards': 'गार्ड कार्ड',
          'settings': 'सेटिंग्स',
          'edit_account_details': 'खाता विवरण संपादित करें',
          'apply_leave': 'छुट्टी लागू करें',
          'reports': 'रिपोर्ट्स',
          'terms_and_conditions': 'शर्तें और नियम',
          'privacy_policy': 'गोपनीयता नीति',
          'language': 'भाषा',
          'help_and_support': 'सहायता और समर्थन',
          'sign_out': 'साइन आउट',
          'notification_alert': 'सूचना अलर्ट ',
          'text_messages': 'टेक्स्ट संदेश',
          'add_guard_card': 'गार्ड कार्ड जोड़ें',
          'required_field': 'कृपया इस फ़ील्ड को भरें!',
          'required_email_text': 'कृपया वैध ईमेल पता दर्ज करें!',
          'required_phone_no_text': 'कृपया वैध मोबाइल नंबर दर्ज करें!',
          'required_upload_guard_card': 'कृपया अपना कार्ड अपलोड करें!',
          'your_reports': 'आपकी रिपोर्टें',
          'recent_reports': 'हाल की रिपोर्टें',
          'filters': 'फिल्टर',
          'title': 'शीर्षक',
          'by_property': 'संपत्ति द्वारा दृश्य',
          'date_range': 'तिथि सीमा',
          'from': 'से',
          'to': 'को',
          'old_password': 'पुराना पासवर्ड',
          'new_password': 'नया पासवर्ड',
          're_enter_new_password': 'नया पासवर्ड फिर से दर्ज करें',
          'changed': 'बदल गया',
          'search_language': 'भाषा खोजें ',
          'log_out_permission_text': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
          'request_logout_task_pending_text':
              'आपकी शिफ़्ट पूरी नहीं हुई है। कार्य लंबित हैं।',
          'leave_from': 'से छुट्टी',
          'terms_and_condition_accepting_message':
              'मैंने नियम और शर्तें स्वीकार की हैं। इस पृष्ठ पर उल्लिखित सभी शर्तों और नियमों को स्वीकार न करें अगर आप सभी नियम और शर्तों को मानते नहीं हैं।',
          'total_missing_shifts_on_leave': 'छुट्टी पर कुल गायब शिफ्टें',
          'leave_reason': 'छुट्टी का कारण',
          'shifts_between_dates': 'तारीखों के बीच शिफ्ट',
          'sent_successfully': 'सफलतापूर्वक भेजा गया',
          'approval_wait_text': 'मंजूरी के लिए प्रतीक्षा करें!',
          'enter_registered_email':'कृपया पंजीकृत ईमेल दर्ज करें',
        },
        'ar': {
          'welcome': 'مرحبًا بعودتك',
          'sign_in': 'تسجيل الدخول للمتابعة',
          'email': 'بريد إلكتروني',
          'enter_email': 'أدخل البريد الإلكتروني',
          'password': 'كلمة المرور',
          'enter_password': 'أدخل كلمة المرور',
          'forget_password': 'نسيت كلمة المرور',
          'sign_in_text': 'تسجيل الدخول',
        },
        'zh': {
          'welcome': '欢迎回来',
          'sign_in': '登录以继续',
          'email': '电子邮件',
          'enter_email': '输入电子邮件',
          'password': '密码',
          'enter_password': '输入密码',
          'forget_password': '忘记密码',
          'sign_in_text': '登入',
        },
        'de': {
          'welcome': 'Willkommen zurück',
          'sign_in': 'Melden Sie sich an, um fortzufahren',
          'email': 'Email',
          'enter_email': 'Email eingeben',
          'password': 'Passwort',
          'enter_password': 'Passwort eingeben',
          'forget_password': 'Passwort vergessen',
          'sign_in_text': 'Anmelden',
        },
        'fr': {
          'welcome': 'Content de te revoir',
          'sign_in': 'Connectez-vous pour continuer',
          'email': 'E-mail',
          'enter_email': 'Entrez votre e-mail',
          'password': 'Mot de passe',
          'enter_password': 'Entrer le mot de passe',
          'forget_password': 'Mot de passe oublié',
          'sign_in_text': 'Se connecter',
        },
        'it': {
          'welcome': 'Bentornato',
          'sign_in': 'Accedi per continuare',
          'email': 'E-mail',
          'enter_email': "Inserisci l'email",
          'password': "Parola d'ordine",
          'enter_password': 'Inserire la password',
          'forget_password': 'Dimenticare la password',
          'sign_in_text': 'Registrazione',
        },
        'ur': {
          'welcome': 'خوش آمدید',
          'sign_in': 'جاری رکھنے کے لیے سائن ان کریں۔',
          'email': 'ای میل',
          'enter_email': 'ای میل درج کریں۔',
          'password': 'پاس ورڈ',
          'enter_password': 'پاس ورڈ درج کریں',
          'forget_password': 'پاس ورڈ بھول جانا',
          'sign_in_text': 'سائن ان',
        },
        'bn': {
          'welcome': 'ফিরে আসার জন্য স্বাগতম',
          'sign_in': 'চালিয়ে যেতে সাইন ইন করুন',
          'email': 'ইমেইল',
          'enter_email': 'ইমেইল প্রদান করুন',
          'password': 'পাসওয়ার্ড',
          'enter_password': 'পাসওয়ার্ড লিখুন',
          'forget_password': 'পাসওয়ার্ড ভুলে গেছেন',
          'sign_in_text': 'সাইন ইন করুন',
        }
      };
}
