// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8UGWEUdZg7o7vw_TpvWlvaRrCxgPYK4o',
    appId: '1:1070413214874:android:242f2b971c2f216ebb1b23',
    messagingSenderId: '1070413214874',
    projectId: 'sgtguardappchat',
    databaseURL: 'https://sgtguardappchat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sgtguardappchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH-tr8ZcDWFNM1Xix5m7l4gQ3P_Kq72nk',
    appId: '1:1070413214874:ios:ff5c368ada5b332cbb1b23',
    messagingSenderId: '1070413214874',
    projectId: 'sgtguardappchat',
    databaseURL: 'https://sgtguardappchat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sgtguardappchat.appspot.com',
    iosBundleId: 'com.dbm123.sgt',
  );
}
